### ISSUE TITLE
deno install scripts failed

### ISSUE THREAD

**Issue by boostbob** [nestdotland/nest#19] opened 2021-04-08 14:54 UTC
Desktop 🍎  deno install -Af https://nest.land/-/nest/nest.ts

```
Download https://nest.land/-/nest/nest.ts
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://nest.land/-/nest/nest.ts
  MediaType: Unknown
```

env:

```
Desktop 🍎  deno --version
deno 1.8.3 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

**Comment by oganexon** [comment] 2021-04-08 15:41
Duplicate of #18
Until the stable release of nest, the current CLI is [eggs](https://github.com/nestdotland/eggs).

**Closed by oganexon** 2021-04-08 15:41 UTC
Labels: bug report, needs triage
